package constants

const (
	CONST_PLAYER_PREFIX = "indpl"
	CONST_NUMBER_FIVE   = 5
)

const (
	DB_STATUS_REGISTERED = 0
	DB_STATUS_ACTIVE     = 1
	DB_STATUS_INACTIVE   = 3
	DB_STATUS_DEACTIVE   = 9
)
